export const WebBuddyESLintIgnores: string[] = [
    //
    'package*.json',
    //
    '*.scss',
    '*.css',
    '*.pcss',
    '*.postcss',
    '*.html',
    '*.htm',
    '!.*.yml',
    '!.*.yaml',
    '!.*.json',
    //
    '*.tmp.*',
    '*.private.*',
    '*.tmp/',
    '*.private/',
    //
    '.husky/_/',
    './.cache/',
    './.*-cache/',
    './.coverage/',
    //
    './dist/',
    './lib/',
    '**/node_modules/',
    '**/vendor/',
    //
    '.iml',
    '.idea/',
    '.vscode/',
    '.history/',
    //
    './spec/*.schema*.json',
    './spec/*.openapi.json',
    './spec/*.dbml.json',
    //
    './jest-setup.ts',
    './*.jest-setup.ts',
];
